-- Supabase Dashboard > SQL Editor에서 실행하세요.
-- 음식점 테이블이 아직 없다면 restaurant_id는 우선 정수로 관리합니다.

CREATE TABLE IF NOT EXISTS public.menu_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT NOT NULL CHECK (restaurant_id > 0),
    name VARCHAR(100) NOT NULL CHECK (char_length(trim(name)) > 0),
    description VARCHAR(500),
    price INTEGER NOT NULL CHECK (price >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_menu_items_restaurant_id
    ON public.menu_items (restaurant_id);

-- 아래 INSERT는 메뉴 10건을 한 번에 넣습니다.
-- id와 created_at은 명시하지 않습니다. id는 IDENTITY가, created_at은 DEFAULT NOW()가 자동 처리합니다.
-- 이 블록을 여러 번 실행하면 같은 메뉴가 중복으로 추가될 수 있습니다.
INSERT INTO public.menu_items (restaurant_id, name, description, price) VALUES
    (1, '불고기 버거', '직화 불고기 패티와 신선한 채소', 7500),
    (1, '치즈 버거', '체다 치즈가 들어간 소고기 패티 버거', 6900),
    (1, '감자튀김', '바삭하게 튀긴 감자 사이드 메뉴', 2500),
    (1, '콜라', '355ml 캔 음료', 2000),
    (2, '마라탕', '맵기와 재료를 선택할 수 있는 마라탕', 12000),
    (2, '꿔바로우', '새콤달콤 소스를 곁들인 찹쌀 탕수육', 15000),
    (2, '마라샹궈', '다양한 재료를 볶은 마라 요리', 18000),
    (3, '페퍼로니 피자', '페퍼로니와 치즈를 올린 8조각 피자', 18900),
    (3, '치즈 오븐 스파게티', '진한 토마토 소스와 모짜렐라 치즈', 9900),
    (3, '치킨 윙', '매콤달콤한 소스의 치킨 윙 6조각', 8500);

-- 팀에서 restaurants 테이블을 만든 뒤에는 다음처럼 FK를 추가할 수 있습니다.
-- ALTER TABLE public.menu_items
-- ADD CONSTRAINT fk_menu_items_restaurant
-- FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id) ON DELETE CASCADE;
