CREATE TABLE IF NOT EXISTS public.products (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    price INTEGER NOT NULL CHECK (price >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. 배달 메뉴 테이블
-- food_delivery.sql과 menu_items.sql의 id 타입 충돌을 해결하기 위해
-- 자동 증가 BIGINT id로 통일했습니다.
CREATE TABLE IF NOT EXISTS public.menu_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT NOT NULL CHECK (restaurant_id > 0),
    name VARCHAR(100) NOT NULL CHECK (char_length(trim(name)) > 0),
    description VARCHAR(500),
    price INTEGER NOT NULL CHECK (price >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_menu_items_restaurant_id
    ON public.menu_items (restaurant_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_menu_items_restaurant_name
    ON public.menu_items (restaurant_id, name);

-- 3. 배달 문의 테이블
-- customer.sql 파일의 실제 내용은 회원 테이블이 아니라 배달 문의 테이블입니다.
CREATE TABLE IF NOT EXISTS public.delivery_inquiries (
    id TEXT PRIMARY KEY,
    member_id TEXT NOT NULL,
    restaurant_id TEXT NOT NULL,
    inquiry_content TEXT NOT NULL CHECK (char_length(trim(inquiry_content)) > 0),
    status TEXT NOT NULL DEFAULT '답변대기'
        CHECK (status IN ('답변대기', '답변완료')),
    answer TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_delivery_inquiries_member_id
    ON public.delivery_inquiries (member_id);

CREATE INDEX IF NOT EXISTS idx_delivery_inquiries_restaurant_id
    ON public.delivery_inquiries (restaurant_id);

-- 4. 메뉴 테스트 데이터
INSERT INTO public.menu_items (restaurant_id, name, description, price) VALUES
    (1, '후라이드 치킨', '바삭하고 담백한 한 마리 치킨', 18000),
    (1, '양념 치킨', '달콤매콤 특제 양념 치킨', 19000),
    (1, '치즈볼', '고소한 모짜렐라 치즈볼 5개', 5000),
    (2, '불맛 짬뽕', '직화 향이 살아있는 해물 짬뽕', 10000),
    (2, '짜장면', '진한 춘장 소스의 짜장면', 7500),
    (2, '탕수육 소', '바삭한 탕수육과 새콤달콤 소스', 18000),
    (3, '참치 김밥', '참치와 채소가 들어간 김밥', 5000),
    (3, '떡볶이', '매콤달콤한 국물 떡볶이', 4500),
    (3, '모둠 튀김', '김말이, 오징어, 야채 튀김', 6000),
    (1, '불고기 버거', '직화 불고기 패티와 신선한 채소', 7500),
    (1, '치즈 버거', '체다 치즈가 들어간 소고기 패티 버거', 6900),
    (1, '감자튀김', '바삭하게 튀긴 감자 사이드 메뉴', 2500),
    (1, '콜라', '355ml 캔 음료', 2000),
    (2, '마라탕', '맵기와 재료를 선택할 수 있는 마라탕', 12000),
    (2, '꿔바로우', '새콤달콤 소스를 곁들인 찹쌀 탕수육', 15000),
    (2, '마라샹궈', '다양한 재료를 볶아낸 마라 요리', 18000),
    (3, '페퍼로니 피자', '페퍼로니와 치즈를 올린 8조각 피자', 18900),
    (3, '치즈 오븐 스파게티', '진한 토마토 소스와 모짜렐라 치즈', 9900),
    (3, '치킨 윙', '매콤달콤 소스의 치킨 윙 6조각', 8500)
ON CONFLICT (restaurant_id, name) DO NOTHING;

-- 5. 배달 문의 테스트 데이터
INSERT INTO public.delivery_inquiries
    (id, member_id, restaurant_id, inquiry_content, status, answer, created_at)
VALUES
    ('20260722100000000001', 'member-001', 'restaurant-001',
     '주문한 음식이 아직 도착하지 않았습니다.', '답변대기', NULL, '2026-07-22 10:00:00+09'),
    ('20260722100500000002', 'member-002', 'restaurant-001',
     '음식이 식어서 도착했어요.', '답변완료', '불편을 드려 죄송합니다. 고객센터에서 확인 후 처리하겠습니다.', '2026-07-22 10:05:00+09'),
    ('20260722101000000003', 'member-003', 'restaurant-002',
     '주문을 취소하고 싶습니다.', '답변대기', NULL, '2026-07-22 10:10:00+09')
ON CONFLICT (id) DO NOTHING;

-- products.sql의 테스트 INSERT는 원본에서 따옴표가 깨져 SQL 실행이 불가능해
-- products 테이블 정의만 포함했습니다. 필요한 상품 데이터는 아래 형식으로 추가하세요.
-- INSERT INTO public.products (id, name, price)
-- VALUES ('product-001', '상품명', 10000)
-- ON CONFLICT (id) DO NOTHING;