-- 배달 음식점 테이블 (PostgreSQL / Supabase)
-- menu_items.restaurant_id의 1, 2, 3번 메뉴 데이터와 연결해서 사용할 수 있습니다.

CREATE TABLE IF NOT EXISTS restaurants (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    address TEXT NOT NULL,
    phone TEXT NOT NULL,
    delivery_fee INTEGER NOT NULL DEFAULT 3000 CHECK (delivery_fee >= 0),
    minimum_order_amount INTEGER NOT NULL DEFAULT 0 CHECK (minimum_order_amount >= 0),
    rating NUMERIC(2, 1) NOT NULL DEFAULT 0 CHECK (rating >= 0 AND rating <= 5),
    is_open BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- 테스트용 배달 음식점 데이터
INSERT INTO restaurants
    (id, name, category, address, phone, delivery_fee, minimum_order_amount, rating, is_open)
VALUES
    (1, '맛있는 치킨', '치킨', '서울특별시 강남구 테헤란로 101', '02-1234-5678', 3000, 15000, 4.7, TRUE),
    (2, '불맛 짬뽕', '중식', '서울특별시 강남구 역삼로 25', '02-2345-6789', 2500, 12000, 4.5, TRUE),
    (3, '오늘의 김밥', '분식', '서울특별시 강남구 봉은사로 80', '02-3456-7890', 2000, 10000, 4.6, TRUE),
    (4, '든든한 한식', '한식', '서울특별시 강남구 삼성로 45', '02-4567-8901', 3000, 14000, 4.4, TRUE),
    (5, '피자 한 판', '피자', '서울특별시 강남구 선릉로 120', '02-5678-9012', 3500, 18000, 4.3, FALSE);

-- 필요하면 menu_items 테이블과 연결하는 외래 키를 추가할 수 있습니다.
-- 기존 menu_items에 restaurant_id 1~5 이외 값이 없을 때만 실행하세요.
-- ALTER TABLE menu_items
-- ADD CONSTRAINT fk_menu_items_restaurant
-- FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE;
